version: "3.1"

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: pg
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

volumes:
  pg-data:
